"""
Generative AI Engine — Tax Summary & Explanation Generator
===========================================================
Generates natural language content using template-based generation
with chain-of-thought reasoning and dynamic content composition.

Capabilities:
1. Auto-fill tax summaries from user data
2. Explain tax calculations in natural language
3. Generate personalized tax advice
4. Chain-of-thought reasoning for complex queries
"""

from typing import Dict, List
from datetime import datetime


class GenerativeEngine:
    """
    Template-based generative AI engine for tax content.

    Uses structured templates with dynamic content injection,
    chain-of-thought reasoning, and role-based generation.
    """

    def __init__(self):
        self.generation_count = 0

    def generate_tax_summary(self, user_data: Dict, tax_result: Dict) -> str:
        """
        Auto-generate a comprehensive tax summary in natural language.

        Uses template-based generation with dynamic content filling.
        """
        name = user_data.get('name', 'Taxpayer')
        income = user_data.get('annual_income', 0)
        regime = tax_result.get('recommended_regime', 'new')
        old_tax = tax_result.get('old_regime', {}).get('total_tax', 0)
        new_tax = tax_result.get('new_regime', {}).get('total_tax', 0)
        savings = tax_result.get('potential_savings', 0)

        best_result = tax_result.get(f'{regime}_regime', {})

        summary = f"""
═══════════════════════════════════════════════════
         TAX FILING SUMMARY — FY 2024-25
═══════════════════════════════════════════════════

📋 TAXPAYER PROFILE
   Name: {name}
   Assessment Year: 2025-26
   Employment: {user_data.get('employment_type', 'Salaried').title()}
   Generated: {datetime.now().strftime('%d %B %Y, %I:%M %p')}

💰 INCOME SUMMARY
   Gross Annual Income: ₹{income:,.0f}
   Other Income: ₹{user_data.get('other_income', 0):,.0f}
   Total Gross Income: ₹{income + user_data.get('other_income', 0):,.0f}

📊 TAX COMPUTATION
   ┌─────────────────────────────────────┐
   │  Recommended Regime: {regime.upper()} REGIME  │
   │  Tax under Old Regime: ₹{old_tax:>10,.0f}  │
   │  Tax under New Regime: ₹{new_tax:>10,.0f}  │
   │  YOUR SAVINGS: ₹{savings:>14,.0f}  │
   └─────────────────────────────────────┘

📝 DETAILED BREAKDOWN ({regime.upper()} REGIME)
   Gross Income:        ₹{income:>12,.0f}
   Standard Deduction: -₹{best_result.get('standard_deduction', 0):>12,.0f}
   Total Deductions:   -₹{best_result.get('total_deductions', 0):>12,.0f}
   ────────────────────────────────────
   Taxable Income:      ₹{best_result.get('taxable_income', 0):>12,.0f}
   Tax on Income:       ₹{best_result.get('tax_before_rebate', 0):>12,.0f}
   Rebate u/s 87A:     -₹{best_result.get('rebate_87a', 0):>12,.0f}
   Surcharge:          +₹{best_result.get('surcharge', 0):>12,.0f}
   Cess (4%):          +₹{best_result.get('cess', 0):>12,.0f}
   ════════════════════════════════════
   TOTAL TAX LIABILITY:  ₹{best_result.get('total_tax', 0):>12,.0f}
   Effective Rate:       {best_result.get('effective_rate', 0):.2f}%

"""

        # Add deduction details for old regime
        if regime == 'old' and best_result.get('deduction_details'):
            summary += "🏦 DEDUCTIONS CLAIMED\n"
            for section, amount in best_result['deduction_details'].items():
                if amount > 0:
                    section_name = section.replace('_', ' ').title()
                    summary += f"   {section_name}: ₹{amount:,.0f}\n"

        summary += f"""
⚡ AI INSIGHTS
   • The {regime} regime saves you ₹{savings:,.0f} compared to the alternative.
   • Your effective tax rate is {best_result.get('effective_rate', 0):.2f}%.
"""

        if best_result.get('effective_rate', 0) > 25:
            summary += "   • Consider additional deductions to lower your effective rate.\n"
        elif best_result.get('effective_rate', 0) < 5:
            summary += "   • Your tax efficiency is excellent! Well-optimized deductions.\n"

        summary += """
═══════════════════════════════════════════════════
 Generated by AI Tax Filing Assistant | Not legal advice
═══════════════════════════════════════════════════
"""
        self.generation_count += 1
        return summary

    def explain_calculation(self, tax_result: Dict, regime: str = 'auto') -> str:
        """
        Generate a chain-of-thought explanation of the tax calculation.

        Uses step-by-step reasoning to explain how the tax was computed.
        """
        if regime == 'auto':
            regime = tax_result.get('recommended_regime', 'new')

        result = tax_result.get(f'{regime}_regime', tax_result)

        explanation = f"""
🧠 CHAIN-OF-THOUGHT TAX CALCULATION EXPLANATION

Let me walk you through how your tax was calculated under the {regime.upper()} regime, step by step:

━━━ Step 1: Start with Gross Income ━━━
Your total gross income is ₹{result.get('gross_income', 0):,.0f}.
This includes salary, allowances, and any other income sources.

━━━ Step 2: Standard Deduction ━━━
As a salaried individual, you get a flat standard deduction of ₹{result.get('standard_deduction', 0):,.0f}.
This is automatically available — no proof needed!
Income after standard deduction: ₹{result.get('gross_income', 0) - result.get('standard_deduction', 0):,.0f}

"""

        if regime == 'old' and result.get('total_deductions', 0) > 0:
            explanation += f"""━━━ Step 3: Chapter VIA Deductions ━━━
Under the old regime, you can claim deductions totaling ₹{result.get('total_deductions', 0):,.0f}.
"""
            if result.get('deduction_details'):
                for section, amount in result['deduction_details'].items():
                    if amount > 0:
                        explanation += f"  ✓ {section.replace('_', ' ').title()}: ₹{amount:,.0f}\n"

            explanation += f"""
These deductions reduce your taxable income significantly!
"""

        explanation += f"""
━━━ Step {'4' if regime == 'old' else '3'}: Taxable Income ━━━
After all deductions, your net taxable income is ₹{result.get('taxable_income', 0):,.0f}.
This is the amount on which tax slabs are applied.

━━━ Step {'5' if regime == 'old' else '4'}: Apply Tax Slabs ━━━
"""

        # Explain slab application
        if regime == 'new':
            explanation += """The new regime has 6 slabs:
  • ₹0 - ₹3,00,000: NIL (0%)
  • ₹3,00,001 - ₹7,00,000: 5%
  • ₹7,00,001 - ₹10,00,000: 10%
  • ₹10,00,001 - ₹12,00,000: 15%
  • ₹12,00,001 - ₹15,00,000: 20%
  • Above ₹15,00,000: 30%
"""
        else:
            explanation += """The old regime has 4 slabs:
  • ₹0 - ₹2,50,000: NIL (0%)
  • ₹2,50,001 - ₹5,00,000: 5%
  • ₹5,00,001 - ₹10,00,000: 20%
  • Above ₹10,00,000: 30%
"""

        explanation += f"""
Tax computed on slabs: ₹{result.get('tax_before_rebate', 0):,.0f}
"""

        if result.get('rebate_87a', 0) > 0:
            explanation += f"""
━━━ Rebate u/s 87A ━━━
Since your taxable income is within the rebate limit, you get a rebate of ₹{result.get('rebate_87a', 0):,.0f}!
Tax after rebate: ₹{result.get('tax_after_rebate', 0):,.0f}
"""

        explanation += f"""
━━━ Final: Cess ━━━
Health & Education Cess of 4% is applied on the tax amount.
Cess amount: ₹{result.get('cess', 0):,.0f}

════════════════════════════════
FINAL TAX LIABILITY: ₹{result.get('total_tax', 0):,.0f}
Effective Tax Rate: {result.get('effective_rate', 0):.2f}%
════════════════════════════════

💡 This means for every ₹100 you earn, you pay approximately ₹{result.get('effective_rate', 0):.1f} as tax.
"""

        return explanation

    def generate_personalized_advice(self, user_data: Dict, tax_result: Dict) -> List[str]:
        """Generate personalized tax-saving advice."""
        advice = []
        income = user_data.get('annual_income', 0)
        regime = tax_result.get('recommended_regime', 'new')

        # Age-based advice
        age = user_data.get('age', 30)
        if age < 30:
            advice.append("🎯 At your age, consider ELSS for 80C — shortest lock-in (3 years) with potential for high returns.")
            advice.append("💡 Start NPS early under 80CCD(1B) for an extra ₹50K deduction + retirement corpus.")

        if age >= 60:
            advice.append("👴 As a senior citizen, you qualify for higher exemption limits and ₹50K interest deduction under 80TTB.")

        # Income-based advice
        if income > 2000000:
            advice.append("⚠️ With income above ₹20L, watch for surcharge applicability. Consider spreading income if possible.")

        if income > 1000000 and regime == 'old':
            advice.append("🏦 Your 30% marginal rate means every ₹1 of deduction saves ₹0.312 in tax (including cess).")

        # Deduction gaps
        investments_80c = user_data.get('investments_80c', 0)
        if investments_80c < 150000:
            gap = 150000 - investments_80c
            advice.append(f"📈 You can still invest ₹{gap:,.0f} more under 80C to maximize this deduction.")

        medical = user_data.get('medical_insurance_80d', 0)
        if medical == 0:
            advice.append("🏥 Get health insurance! ₹25K-₹1L deduction under 80D PLUS medical coverage.")

        nps = user_data.get('nps_contribution', 0)
        if nps < 50000:
            advice.append(f"🏛️ Consider NPS contribution — extra ₹{50000-nps:,.0f} deduction available under 80CCD(1B).")

        home_loan = user_data.get('home_loan_interest', 0)
        if home_loan > 0 and home_loan < 200000:
            advice.append(f"🏠 Your home loan interest deduction has ₹{200000-home_loan:,.0f} room under Section 24(b).")

        return advice

    def generate_what_if_narrative(self, scenarios: Dict) -> str:
        """Generate a narrative explanation of what-if analysis results."""
        base = scenarios.get('base_case', {})
        results = scenarios.get('scenarios', [])

        narrative = f"""
🔮 WHAT-IF TAX ANALYSIS

Your current tax liability: ₹{base.get('tax', 0):,.0f} (under {base.get('regime', 'N/A')} regime)

Let's see how different scenarios affect your tax:

"""
        for i, scenario in enumerate(results, 1):
            savings = scenario.get('savings_vs_base', 0)
            emoji = "✅" if savings > 0 else ("⚠️" if savings < 0 else "➡️")

            narrative += f"""
{emoji} Scenario {i}: {scenario.get('scenario_name', 'Unknown')}
   Changes: {', '.join(f"{k}: ₹{v:,.0f}" for k, v in scenario.get('changes', {}).items())}
   Tax: ₹{scenario.get('total_tax', 0):,.0f} ({scenario.get('best_regime', 'N/A')} regime)
   {'Savings' if savings >= 0 else 'Additional Cost'}: ₹{abs(savings):,.0f}
"""

        # Best scenario
        if results:
            best = max(results, key=lambda x: x.get('savings_vs_base', 0))
            narrative += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🏆 BEST SCENARIO: {best.get('scenario_name', 'Unknown')}
   Maximum possible savings: ₹{best.get('savings_vs_base', 0):,.0f}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
"""

        return narrative


# Module-level instance
generative_engine = GenerativeEngine()
